### ISSUE TITLE
Change table max-height

### ISSUE THREAD

**Issue by it-sova** [Spinorog/spinorog.github.io#1]
Current table height makes me cry on my monitor, could you kindly change it from static height to 100%?
```css
element.style {
    padding-bottom: 84px;
    height: 734px;
}
```
